export type Pergunta = {
  id: number;
  codigo: string;
  diretoria: string;
  dimensao: string;
  texto: string;
};

export const perguntas: Pergunta[] = [
  // DIRETORIA EXECUTIVA

  {
    id: 1,
    codigo: "EXE-01",
    diretoria: "Diretoria Executiva",
    dimensao: "Planejamento estratégico",
    texto: "A Empresa Júnior possui objetivos estratégicos definidos para o período de gestão atual.",
  },
  {
    id: 2,
    codigo: "EXE-02",
    diretoria: "Diretoria Executiva",
    dimensao: "Planejamento estratégico",
    texto: "As metas estratégicas são desdobradas em ações ou planos executáveis pelas diretorias.",
  },
  {
    id: 3,
    codigo: "EXE-03",
    diretoria: "Diretoria Executiva",
    dimensao: "Planejamento estratégico",
    texto: "A Diretoria Executiva acompanha periodicamente o andamento das metas definidas.",
  },
  {
    id: 4,
    codigo: "EXE-04",
    diretoria: "Diretoria Executiva",
    dimensao: "Governança e tomada de decisão",
    texto: "As principais decisões da Empresa Júnior seguem critérios claros e são registradas de alguma forma.",
  },
  {
    id: 5,
    codigo: "EXE-05",
    diretoria: "Diretoria Executiva",
    dimensao: "Governança e tomada de decisão",
    texto: "Existe uma rotina definida para reuniões de alinhamento entre a Diretoria Executiva e as demais diretorias.",
  },
  {
    id: 6,
    codigo: "EXE-06",
    diretoria: "Diretoria Executiva",
    dimensao: "Governança e tomada de decisão",
    texto: "As responsabilidades da Diretoria Executiva e das demais áreas estão claramente definidas.",
  },
  {
    id: 7,
    codigo: "EXE-07",
    diretoria: "Diretoria Executiva",
    dimensao: "Gestão de desempenho organizacional",
    texto: "A Empresa Júnior utiliza indicadores para acompanhar seu desempenho geral.",
  },
  {
    id: 8,
    codigo: "EXE-08",
    diretoria: "Diretoria Executiva",
    dimensao: "Gestão de desempenho organizacional",
    texto: "Os resultados das diretorias são analisados pela Diretoria Executiva para apoiar decisões de gestão.",
  },
  {
    id: 9,
    codigo: "EXE-09",
    diretoria: "Diretoria Executiva",
    dimensao: "Gestão de desempenho organizacional",
    texto: "Quando os resultados ficam abaixo do esperado, são definidas ações corretivas.",
  },
  {
    id: 10,
    codigo: "EXE-10",
    diretoria: "Diretoria Executiva",
    dimensao: "Comunicação e alinhamento interno",
    texto: "As informações relevantes sobre decisões, metas e prioridades são comunicadas de forma clara aos membros.",
  },
  {
    id: 11,
    codigo: "EXE-11",
    diretoria: "Diretoria Executiva",
    dimensao: "Comunicação e alinhamento interno",
    texto: "Há canais ou rotinas definidos para integração entre as diretorias.",
  },
  {
    id: 12,
    codigo: "EXE-12",
    diretoria: "Diretoria Executiva",
    dimensao: "Comunicação e alinhamento interno",
    texto: "Os membros compreendem como suas atividades contribuem para os objetivos gerais da Empresa Júnior.",
  },

  // DIRETORIA COMERCIAL

  {
    id: 13,
    codigo: "COM-01",
    diretoria: "Diretoria Comercial",
    dimensao: "Prospecção e geração de oportunidades",
    texto: "A Diretoria Comercial possui um processo definido para identificar e prospectar potenciais clientes.",
  },
  {
    id: 14,
    codigo: "COM-02",
    diretoria: "Diretoria Comercial",
    dimensao: "Prospecção e geração de oportunidades",
    texto: "As oportunidades comerciais são registradas em alguma ferramenta, planilha ou sistema de acompanhamento.",
  },
  {
    id: 15,
    codigo: "COM-03",
    diretoria: "Diretoria Comercial",
    dimensao: "Prospecção e geração de oportunidades",
    texto: "A prospecção é realizada de forma recorrente, e não apenas quando há baixa demanda por projetos.",
  },
  {
    id: 16,
    codigo: "COM-04",
    diretoria: "Diretoria Comercial",
    dimensao: "Gestão do funil comercial",
    texto: "A área comercial acompanha as etapas do funil de vendas, desde o primeiro contato até o fechamento.",
  },
  {
    id: 17,
    codigo: "COM-05",
    diretoria: "Diretoria Comercial",
    dimensao: "Gestão do funil comercial",
    texto: "Existe controle sobre propostas enviadas, negociações em andamento e oportunidades perdidas.",
  },
  {
    id: 18,
    codigo: "COM-06",
    diretoria: "Diretoria Comercial",
    dimensao: "Gestão do funil comercial",
    texto: "A diretoria analisa motivos de perda de clientes ou de não fechamento de propostas.",
  },
  {
    id: 19,
    codigo: "COM-07",
    diretoria: "Diretoria Comercial",
    dimensao: "Propostas e negociação",
    texto: "A Empresa Júnior possui um padrão ou modelo para elaboração de propostas comerciais.",
  },
  {
    id: 20,
    codigo: "COM-08",
    diretoria: "Diretoria Comercial",
    dimensao: "Propostas e negociação",
    texto: "As propostas comerciais consideram escopo, prazo, preço e capacidade real de entrega da equipe.",
  },
  {
    id: 21,
    codigo: "COM-09",
    diretoria: "Diretoria Comercial",
    dimensao: "Propostas e negociação",
    texto: "A precificação dos projetos segue critérios definidos, e não apenas decisões informais ou estimativas pontuais.",
  },
  {
    id: 22,
    codigo: "COM-10",
    diretoria: "Diretoria Comercial",
    dimensao: "Relacionamento com clientes",
    texto: "A Diretoria Comercial mantém registros sobre clientes atendidos, contatos realizados e histórico de relacionamento.",
  },
  {
    id: 23,
    codigo: "COM-11",
    diretoria: "Diretoria Comercial",
    dimensao: "Relacionamento com clientes",
    texto: "Existe acompanhamento após o fechamento da venda para garantir transição adequada para a área de projetos.",
  },
  {
    id: 24,
    codigo: "COM-12",
    diretoria: "Diretoria Comercial",
    dimensao: "Relacionamento com clientes",
    texto: "A Empresa Júnior realiza algum tipo de contato ou ação para manter relacionamento com clientes após a entrega do projeto.",
  },

  // DIRETORIA DE PROJETOS

  {
    id: 25,
    codigo: "PROJ-01",
    diretoria: "Diretoria de Projetos",
    dimensao: "Planejamento de projetos",
    texto: "Os projetos são iniciados com definição clara de escopo, entregas, prazos e responsáveis.",
  },
  {
    id: 26,
    codigo: "PROJ-02",
    diretoria: "Diretoria de Projetos",
    dimensao: "Planejamento de projetos",
    texto: "Antes do início de um projeto, a equipe avalia se possui capacidade técnica e disponibilidade para executá-lo.",
  },
  {
    id: 27,
    codigo: "PROJ-03",
    diretoria: "Diretoria de Projetos",
    dimensao: "Planejamento de projetos",
    texto: "O planejamento do projeto é registrado em alguma ferramenta, documento ou sistema de acompanhamento.",
  },
  {
    id: 28,
    codigo: "PROJ-04",
    diretoria: "Diretoria de Projetos",
    dimensao: "Execução e acompanhamento",
    texto: "A Diretoria de Projetos acompanha regularmente o andamento dos projetos em execução.",
  },
  {
    id: 29,
    codigo: "PROJ-05",
    diretoria: "Diretoria de Projetos",
    dimensao: "Execução e acompanhamento",
    texto: "A equipe identifica atrasos, mudanças de escopo ou dificuldades técnicas durante a execução do projeto.",
  },
  {
    id: 30,
    codigo: "PROJ-06",
    diretoria: "Diretoria de Projetos",
    dimensao: "Execução e acompanhamento",
    texto: "Quando ocorrem problemas na execução, são definidas ações para corrigir ou reduzir os impactos.",
  },
  {
    id: 31,
    codigo: "PROJ-07",
    diretoria: "Diretoria de Projetos",
    dimensao: "Comunicação com o cliente",
    texto: "Existe uma rotina definida de comunicação com o cliente durante a execução do projeto.",
  },
  {
    id: 32,
    codigo: "PROJ-08",
    diretoria: "Diretoria de Projetos",
    dimensao: "Comunicação com o cliente",
    texto: "O cliente é informado sobre andamento, entregas, prazos e eventuais mudanças no projeto.",
  },
  {
    id: 33,
    codigo: "PROJ-09",
    diretoria: "Diretoria de Projetos",
    dimensao: "Comunicação com o cliente",
    texto: "As decisões e alterações combinadas com o cliente são registradas para evitar perda de informações.",
  },
  {
    id: 34,
    codigo: "PROJ-10",
    diretoria: "Diretoria de Projetos",
    dimensao: "Qualidade e encerramento",
    texto: "A Empresa Júnior possui critérios para verificar a qualidade das entregas realizadas.",
  },
  {
    id: 35,
    codigo: "PROJ-11",
    diretoria: "Diretoria de Projetos",
    dimensao: "Qualidade e encerramento",
    texto: "Ao final dos projetos, são coletados feedbacks do cliente ou da equipe envolvida.",
  },
  {
    id: 36,
    codigo: "PROJ-12",
    diretoria: "Diretoria de Projetos",
    dimensao: "Qualidade e encerramento",
    texto: "As experiências e aprendizados dos projetos concluídos são registrados para melhorar projetos futuros.",
  },

  // DIRETORIA ADMINISTRATIVA

  {
    id: 37,
    codigo: "ADM-01",
    diretoria: "Diretoria Administrativa",
    dimensao: "Gestão financeira",
    texto: "A Empresa Júnior mantém controle atualizado de entradas, saídas e saldo financeiro.",
  },
  {
    id: 38,
    codigo: "ADM-02",
    diretoria: "Diretoria Administrativa",
    dimensao: "Gestão financeira",
    texto: "As movimentações financeiras são registradas de forma organizada e acessível para consulta.",
  },
  {
    id: 39,
    codigo: "ADM-03",
    diretoria: "Diretoria Administrativa",
    dimensao: "Gestão financeira",
    texto: "A diretoria utiliza informações financeiras para apoiar decisões, planejamento e definição de prioridades.",
  },
  {
    id: 40,
    codigo: "ADM-04",
    diretoria: "Diretoria Administrativa",
    dimensao: "Documentação e conformidade",
    texto: "A Empresa Júnior mantém seus documentos institucionais organizados e atualizados.",
  },
  {
    id: 41,
    codigo: "ADM-05",
    diretoria: "Diretoria Administrativa",
    dimensao: "Documentação e conformidade",
    texto: "Existe controle sobre contratos, termos, atas, registros ou documentos importantes da organização.",
  },
  {
    id: 42,
    codigo: "ADM-06",
    diretoria: "Diretoria Administrativa",
    dimensao: "Documentação e conformidade",
    texto: "A diretoria acompanha prazos, obrigações administrativas ou necessidades de atualização documental.",
  },
  {
    id: 43,
    codigo: "ADM-07",
    diretoria: "Diretoria Administrativa",
    dimensao: "Processos internos",
    texto: "As principais rotinas administrativas da Empresa Júnior estão definidas e documentadas.",
  },
  {
    id: 44,
    codigo: "ADM-08",
    diretoria: "Diretoria Administrativa",
    dimensao: "Processos internos",
    texto: "As atividades administrativas não dependem exclusivamente do conhecimento informal de membros específicos.",
  },
  {
    id: 45,
    codigo: "ADM-09",
    diretoria: "Diretoria Administrativa",
    dimensao: "Processos internos",
    texto: "A transição de responsabilidades entre gestões ou membros ocorre de forma organizada.",
  },
  {
    id: 46,
    codigo: "ADM-10",
    diretoria: "Diretoria Administrativa",
    dimensao: "Organização de dados e informações",
    texto: "A Empresa Júnior possui uma forma organizada de armazenar informações importantes sobre sua operação.",
  },
  {
    id: 47,
    codigo: "ADM-11",
    diretoria: "Diretoria Administrativa",
    dimensao: "Organização de dados e informações",
    texto: "Os dados administrativos podem ser acessados com facilidade pelos responsáveis quando necessário.",
  },
  {
    id: 48,
    codigo: "ADM-12",
    diretoria: "Diretoria Administrativa",
    dimensao: "Organização de dados e informações",
    texto: "A diretoria utiliza registros e dados internos para acompanhar a situação administrativa da Empresa Júnior.",
  },
];